package dev.vinyard.adventofcode.soluce.year2022.day9;

import dev.vinyard.aoc.plugins.solution.api.Solution;
import dev.vinyard.aoc.plugins.solution.api.annotation.AdventOfCodeSolution;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

@AdventOfCodeSolution(year = 2022, day = 9, part = 1, description = "Rope Bridge", link = "https://adventofcode.com/2022/day/9", tags = "unsolved")
public class Day9Part1Solution implements Solution<Long> {

    /**
    * <h2>--- Day 9: Rope Bridge ---</h2>
    * <p>This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.</p>
    * <p>It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.</p>
    * <p>You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where <b>not</b> to step.</p>
    * <p>Consider a rope with a knot at each end; these knots mark the <b>head</b> and the <b>tail</b> of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.</p>
    * <p>Due to nebulous reasoning involving <a href="https://en.wikipedia.org/wiki/Planck_units#Planck_length">Planck lengths</a>, you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical <b>series of motions</b> (your puzzle input) for the head, you can determine how the tail will move.</p>
    * <p>Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must <b>always be touching</b> (diagonally adjacent and even overlapping both count as touching):</p>
    * <pre>
    * ....
    * .TH.
    * ....
    * 
    * ....
    * .H..
    * ..T.
    * ....
    * 
    * ...
    * .H. (H covers T)
    * ...
    * </pre>
    * <p>If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:</p>
    * <pre>
    * .....    .....    .....
    * .TH.. -&gt; .T.H. -&gt; ..TH.
    * .....    .....    .....
    * 
    * ...    ...    ...
    * .T.    .T.    ...
    * .H. -&gt; ... -&gt; .T.
    * ...    .H.    .H.
    * ...    ...    ...
    * </pre>
    * <p>Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:</p>
    * <pre>
    * .....    .....    .....
    * .....    ..H..    ..H..
    * ..H.. -&gt; ..... -&gt; ..T..
    * .T...    .T...    .....
    * .....    .....    .....
    * 
    * .....    .....    .....
    * .....    .....    .....
    * ..H.. -&gt; ...H. -&gt; ..TH.
    * .T...    .T...    .....
    * .....    .....    .....
    * </pre>
    * <p>You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.</p>
    * <p>For example:</p>
    * <pre>
    * R 4
    * U 4
    * L 3
    * D 1
    * R 4
    * D 1
    * L 5
    * R 2
    * </pre>
    * <p>This series of motions moves the head <b>right</b> four steps, then <b>up</b> four steps, then <b>left</b> three steps, then <b>down</b> one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):</p>
    * <pre>
    * == Initial State ==
    * 
    * ......
    * ......
    * ......
    * ......
    * H.....  (H covers T, s)
    * 
    * == R 4 ==
    * 
    * ......
    * ......
    * ......
    * ......
    * TH....  (T covers s)
    * 
    * ......
    * ......
    * ......
    * ......
    * sTH...
    * 
    * ......
    * ......
    * ......
    * ......
    * s.TH..
    * 
    * ......
    * ......
    * ......
    * ......
    * s..TH.
    * 
    * == U 4 ==
    * 
    * ......
    * ......
    * ......
    * ....H.
    * s..T..
    * 
    * ......
    * ......
    * ....H.
    * ....T.
    * s.....
    * 
    * ......
    * ....H.
    * ....T.
    * ......
    * s.....
    * 
    * ....H.
    * ....T.
    * ......
    * ......
    * s.....
    * 
    * == L 3 ==
    * 
    * ...H..
    * ....T.
    * ......
    * ......
    * s.....
    * 
    * ..HT..
    * ......
    * ......
    * ......
    * s.....
    * 
    * .HT...
    * ......
    * ......
    * ......
    * s.....
    * 
    * == D 1 ==
    * 
    * ..T...
    * .H....
    * ......
    * ......
    * s.....
    * 
    * == R 4 ==
    * 
    * ..T...
    * ..H...
    * ......
    * ......
    * s.....
    * 
    * ..T...
    * ...H..
    * ......
    * ......
    * s.....
    * 
    * ......
    * ...TH.
    * ......
    * ......
    * s.....
    * 
    * ......
    * ....TH
    * ......
    * ......
    * s.....
    * 
    * == D 1 ==
    * 
    * ......
    * ....T.
    * .....H
    * ......
    * s.....
    * 
    * == L 5 ==
    * 
    * ......
    * ....T.
    * ....H.
    * ......
    * s.....
    * 
    * ......
    * ....T.
    * ...H..
    * ......
    * s.....
    * 
    * ......
    * ......
    * ..HT..
    * ......
    * s.....
    * 
    * ......
    * ......
    * .HT...
    * ......
    * s.....
    * 
    * ......
    * ......
    * HT....
    * ......
    * s.....
    * 
    * == R 2 ==
    * 
    * ......
    * ......
    * .H....  (H covers T)
    * ......
    * s.....
    * 
    * ......
    * ......
    * .TH...
    * ......
    * s.....
    * </pre>
    * <p>After simulating the rope, you can count up all of the positions the <b>tail visited at least once</b>. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:</p>
    * <pre>
    * ..##..
    * ...##.
    * .####.
    * ....#.
    * s###..
    * </pre>
    * <p>So, there are <b>13</b> positions the tail visited at least once.</p>
    * <p>Simulate your complete hypothetical series of motions. <b>How many positions does the tail of the rope visit at least once?</b></p>
    */
    @Override
    public Long solve(String input) {
        CharStream charStream = CharStreams.fromString(input);

        SolutionLexer lexer = new SolutionLexer(charStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        SolutionParser parser = new SolutionParser(tokens);

        ASD.Root root = parser.root().out;

        return root.part1();
    }
}
