package dev.vinyard.adventofcode.soluce.year2024.day8;

import dev.vinyard.aoc.plugins.solution.api.Solution;
import dev.vinyard.aoc.plugins.solution.api.annotation.AdventOfCodeSolution;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

@AdventOfCodeSolution(year = 2024, day = 8, part = 1, description = "Resonant Collinearity", link = "https://adventofcode.com/2024/day/8", tags = "unsolved")
public class Day8Part1Solution implements Solution<Object> {

    /**
    * <h2>--- Day 8: Resonant Collinearity ---</h2>
    * <p>You find yourselves on the <a href="/2016/day/25">roof</a> of a top-secret Easter Bunny installation.</p>
    * <p>While The Historians do their thing, you take a look at the familiar <b>huge antenna</b>. Much to your surprise, it seems to have been reconfigured to emit a signal that makes people 0.1% more likely to buy Easter Bunny brand Imitation Mediocre Chocolate as a Christmas gift! Unthinkable!</p>
    * <p>Scanning across the city, you find that there are actually many such antennas. Each antenna is tuned to a specific <b>frequency</b> indicated by a single lowercase letter, uppercase letter, or digit. You create a map (your puzzle input) of these antennas. For example:</p>
    * <pre>
    * ............
    * ........0...
    * .....0......
    * .......0....
    * ....0.......
    * ......A.....
    * ............
    * ............
    * ........A...
    * .........A..
    * ............
    * ............
    * </pre>
    * <p>The signal only applies its nefarious effect at specific <b>antinodes</b> based on the resonant frequencies of the antennas. In particular, an antinode occurs at any point that is perfectly in line with two antennas of the same frequency - but only when one of the antennas is twice as far away as the other. This means that for any pair of antennas with the same frequency, there are two antinodes, one on either side of them.</p>
    * <p>So, for these two antennas with frequency a, they create the two antinodes marked with #:</p>
    * <pre>
    * ..........
    * ...#......
    * ..........
    * ....a.....
    * ..........
    * .....a....
    * ..........
    * ......#...
    * ..........
    * ..........
    * </pre>
    * <p>Adding a third antenna with the same frequency creates several more antinodes. It would ideally add four antinodes, but two are off the right side of the map, so instead it adds only two:</p>
    * <pre>
    * ..........
    * ...#......
    * #.........
    * ....a.....
    * ........a.
    * .....a....
    * ..#.......
    * ......#...
    * ..........
    * ..........
    * </pre>
    * <p>Antennas with different frequencies don't create antinodes; A and a count as different frequencies. However, antinodes <b>can</b> occur at locations that contain antennas. In this diagram, the lone antenna with frequency capital A creates no antinodes but has a lowercase-a-frequency antinode at its location:</p>
    * <pre>
    * ..........
    * ...#......
    * #.........
    * ....a.....
    * ........a.
    * .....a....
    * ..#.......
    * ......A...
    * ..........
    * ..........
    * </pre>
    * <p>The first example has antennas with two different frequencies, so the antinodes they create look like this, plus an antinode overlapping the topmost A-frequency antenna:</p>
    * <pre>
    * ......#....#
    * ...#....0...
    * ....#0....#.
    * ..#....0....
    * ....0....#..
    * .#....A.....
    * ...#........
    * #......#....
    * ........A...
    * .........A..
    * ..........#.
    * ..........#.
    * </pre>
    * <p>Because the topmost A-frequency antenna overlaps with a 0-frequency antinode, there are <b>14</b> total unique locations that contain an antinode within the bounds of the map.</p>
    * <p>Calculate the impact of the signal. <b>How many unique locations within the bounds of the map contain an antinode?</b></p>
    */
    @Override
    public Object solve(String input) {
        CharStream charStream = CharStreams.fromString(input);

        SolutionLexer lexer = new SolutionLexer(charStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        SolutionParser parser = new SolutionParser(tokens);

        ASD.Root root = parser.root().out;

        return root.reducingAntennas().countAntinodes();
    }
}
