package dev.vinyard.adventofcode.soluce.year2023.day11;

import dev.vinyard.aoc.plugins.solution.api.Solution;
import dev.vinyard.aoc.plugins.solution.api.annotation.AdventOfCodeSolution;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

@AdventOfCodeSolution(year = 2023, day = 11, part = 1, description = "Cosmic Expansion", link = "https://adventofcode.com/2023/day/11", tags = "unsolved")
public class Day11Part1Solution implements Solution<Object> {

    /**
    * <h2>--- Day 11: Cosmic Expansion ---</h2>
    * <p>You continue following signs for "Hot Springs" and eventually come across an <a href="https://en.wikipedia.org/wiki/Observatory">observatory</a>. The Elf within turns out to be a researcher studying cosmic expansion using the giant telescope here.</p>
    * <p>He doesn't know anything about the missing machine parts; he's only visiting for this research project. However, he confirms that the hot springs are the next-closest area likely to have people; he'll even take you straight there once he's done with today's observation analysis.</p>
    * <p>Maybe you can help him with the analysis to speed things up?</p>
    * <p>The researcher has collected a bunch of data and compiled the data into a single giant <b>image</b> (your puzzle input). The image includes <b>empty space</b> (.) and <b>galaxies</b> (#). For example:</p>
    * <pre>
    * ...#......
    * .......#..
    * #.........
    * ..........
    * ......#...
    * .#........
    * .........#
    * ..........
    * .......#..
    * #...#.....
    * </pre>
    * <p>The researcher is trying to figure out the sum of the lengths of the <b>shortest path between every pair of galaxies</b>. However, there's a catch: the universe expanded in the time it took the light from those galaxies to reach the observatory.</p>
    * <p>Due to something involving gravitational effects, <b>only some space expands</b>. In fact, the result is that <b>any rows or columns that contain no galaxies</b> should all actually be twice as big.</p>
    * <p>In the above example, three columns and two rows contain no galaxies:</p>
    * <pre>
    *    v  v  v
    *  ...#......
    *  .......#..
    *  #.........
    * &gt;..........&lt;
    *  ......#...
    *  .#........
    *  .........#
    * &gt;..........&lt;
    *  .......#..
    *  #...#.....
    *    ^  ^  ^
    * </pre>
    * <p>These rows and columns need to be <b>twice as big</b>; the result of cosmic expansion therefore looks like this:</p>
    * <pre>
    * ....#........
    * .........#...
    * #............
    * .............
    * .............
    * ........#....
    * .#...........
    * ............#
    * .............
    * .............
    * .........#...
    * #....#.......
    * </pre>
    * <p>Equipped with this expanded universe, the shortest path between every pair of galaxies can be found. It can help to assign every galaxy a unique number:</p>
    * <pre>
    * ....1........
    * .........2...
    * 3............
    * .............
    * .............
    * ........4....
    * .5...........
    * ............6
    * .............
    * .............
    * .........7...
    * 8....9.......
    * </pre>
    * <p>In these 9 galaxies, there are <b>36 pairs</b>. Only count each pair once; order within the pair doesn't matter. For each pair, find any shortest path between the two galaxies using only steps that move up, down, left, or right exactly one . or # at a time. (The shortest path between two galaxies is allowed to pass through another galaxy.)</p>
    * <p>For example, here is one of the shortest paths between galaxies 5 and 9:</p>
    * <pre>
    * ....1........
    * .........2...
    * 3............
    * .............
    * .............
    * ........4....
    * .5...........
    * .##.........6
    * ..##.........
    * ...##........
    * ....##...7...
    * 8....9.......
    * </pre>
    * <p>This path has length <b>9</b> because it takes a minimum of <b>nine steps</b> to get from galaxy 5 to galaxy 9 (the eight locations marked # plus the step onto galaxy 9 itself). Here are some other example shortest path lengths:</p>
    * <ul>
    *  <li>Between galaxy 1 and galaxy 7: 15</li>
    *  <li>Between galaxy 3 and galaxy 6: 17</li>
    *  <li>Between galaxy 8 and galaxy 9: 5</li>
    * </ul>
    * <p>In this example, after expanding the universe, the sum of the shortest path between all 36 pairs of galaxies is <b>374</b>.</p>
    * <p>Expand the universe, then find the length of the shortest path between every pair of galaxies. <b>What is the sum of these lengths?</b></p>
    */
    @Override
    public Object solve(String input) {
        CharStream charStream = CharStreams.fromString(input);

        SolutionLexer lexer = new SolutionLexer(charStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        SolutionParser parser = new SolutionParser(tokens);

        ASD.Root root = parser.root().out;

        return root.calculateSumOfShortestPathBetweenEveryPairOfGalaxies(2);
    }
}
