package dev.vinyard.adventofcode.soluce.year2025.day7;

import dev.vinyard.aoc.plugins.solution.api.Solution;
import dev.vinyard.aoc.plugins.solution.api.annotation.AdventOfCodeSolution;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

@AdventOfCodeSolution(year = 2025, day = 7, part = 1, description = "Laboratories", link = "https://adventofcode.com/2025/day/7", tags = "unsolved")
public class Day7Part1Solution implements Solution<Long> {

    /**
    * <h2>--- Day 7: Laboratories ---</h2>
    * <p>You thank the cephalopods for the help and exit the trash compactor, finding yourself in the <a href="/2024/day/6">familiar</a> <a href="/2018/day/4">halls</a> of a North Pole research wing.</p>
    * <p>Based on the large sign that says "teleporter hub", they seem to be researching <b>teleportation</b>; you can't help but try it for yourself and step onto the large yellow teleporter pad.</p>
    * <p>Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking <a href="https://en.wikipedia.org/wiki/Magic_smoke">magic smoke</a>.</p>
    * <p>Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the <b>tachyon manifolds</b>.</p>
    * <p>You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move <b>downward</b>. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.</p>
    * <p>For example:</p>
    * <pre>
    * .......S.......
    * ...............
    * .......^.......
    * ...............
    * ......^.^......
    * ...............
    * .....^.^.^.....
    * ...............
    * ....^.^...^....
    * ...............
    * ...^.^...^.^...
    * ...............
    * ..^...^.....^..
    * ...............
    * .^.^.^.^.^...^.
    * ...............
    * </pre>
    * <p>In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * .......^.......
    * ...............
    * ......^.^......
    * ...............
    * .....^.^.^.....
    * ...............
    * ....^.^...^....
    * ...............
    * ...^.^...^.^...
    * ...............
    * ..^...^.....^..
    * ...............
    * .^.^.^.^.^...^.
    * ...............
    * </pre>
    * <p>At that point, the original beam stops, and two new beams are emitted from the splitter:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * ......|^|......
    * ...............
    * ......^.^......
    * ...............
    * .....^.^.^.....
    * ...............
    * ....^.^...^....
    * ...............
    * ...^.^...^.^...
    * ...............
    * ..^...^.....^..
    * ...............
    * .^.^.^.^.^...^.
    * ...............
    * </pre>
    * <p>Those beams continue downward until they reach more splitters:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * ......|^|......
    * ......|.|......
    * ......^.^......
    * ...............
    * .....^.^.^.....
    * ...............
    * ....^.^...^....
    * ...............
    * ...^.^...^.^...
    * ...............
    * ..^...^.....^..
    * ...............
    * .^.^.^.^.^...^.
    * ...............
    * </pre>
    * <p>At this point, the two splitters create a total of only <b>three</b> tachyon beams, since they are both dumping tachyons into the same place between them:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * ......|^|......
    * ......|.|......
    * .....|^|^|.....
    * ...............
    * .....^.^.^.....
    * ...............
    * ....^.^...^....
    * ...............
    * ...^.^...^.^...
    * ...............
    * ..^...^.....^..
    * ...............
    * .^.^.^.^.^...^.
    * ...............
    * </pre>
    * <p>This process continues until all of the tachyon beams reach a splitter or exit the manifold:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * ......|^|......
    * ......|.|......
    * .....|^|^|.....
    * .....|.|.|.....
    * ....|^|^|^|....
    * ....|.|.|.|....
    * ...|^|^|||^|...
    * ...|.|.|||.|...
    * ..|^|^|||^|^|..
    * ..|.|.|||.|.|..
    * .|^|||^||.||^|.
    * .|.|||.||.||.|.
    * |^|^|^|^|^|||^|
    * |.|.|.|.|.|||.|
    * </pre>
    * <p>To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of <b>21</b> times.</p>
    * <p>Analyze your manifold diagram. <b>How many times will the beam be split?</b></p>
    */
    @Override
    public Long solve(String input) {
        CharStream charStream = CharStreams.fromString(input);

        SolutionLexer lexer = new SolutionLexer(charStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        SolutionParser parser = new SolutionParser(tokens);
        
        ASD.Root root = parser.root().out;

        return root.solution1();
    }
}
