package dev.vinyard.adventofcode.soluce.year2025.day7;

import dev.vinyard.aoc.plugins.solution.api.Solution;
import dev.vinyard.aoc.plugins.solution.api.annotation.AdventOfCodeSolution;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

@AdventOfCodeSolution(year = 2025, day = 7, part = 2, description = "Laboratories", link = "https://adventofcode.com/2025/day/7", tags = "unsolved")
public class Day7Part2Solution implements Solution<Long> {

    /**
    * <h2>--- Part Two ---</h2>
    * <p>With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a <b>quantum tachyon manifold</b>.</p>
    * <p>With a quantum tachyon manifold, only a <b>single tachyon particle</b> is sent through the manifold. A tachyon particle takes <b>both</b> the left and right path of each splitter encountered.</p>
    * <p>Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually <b>time itself</b> which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.</p>
    * <p>To fix the manifold, what you really need to know is the <b>number of timelines</b> active after a single particle completes all of its possible journeys through the manifold.</p>
    * <p>In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * ......|^.......
    * ......|........
    * .....|^.^......
    * .....|.........
    * ....|^.^.^.....
    * ....|..........
    * ...|^.^...^....
    * ...|...........
    * ..|^.^...^.^...
    * ..|............
    * .|^...^.....^..
    * .|.............
    * |^.^.^.^.^...^.
    * |..............
    * </pre>
    * <p>Or, there's the timeline where the particle alternated going left and right at each splitter:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * ......|^.......
    * ......|........
    * ......^|^......
    * .......|.......
    * .....^|^.^.....
    * ......|........
    * ....^.^|..^....
    * .......|.......
    * ...^.^.|.^.^...
    * .......|.......
    * ..^...^|....^..
    * .......|.......
    * .^.^.^|^.^...^.
    * ......|........
    * </pre>
    * <p>Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:</p>
    * <pre>
    * .......S.......
    * .......|.......
    * ......|^.......
    * ......|........
    * .....|^.^......
    * .....|.........
    * ....|^.^.^.....
    * ....|..........
    * ....^|^...^....
    * .....|.........
    * ...^.^|..^.^...
    * ......|........
    * ..^..|^.....^..
    * .....|.........
    * .^.^.^|^.^...^.
    * ......|........
    * </pre>
    * <p>In this example, in total, the particle ends up on <b>40</b> different timelines.</p>
    * <p>Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. <b>In total, how many different timelines would a single tachyon particle end up on?</b></p>
    */
    @Override
    public Long solve(String input) {
        CharStream charStream = CharStreams.fromString(input);

        SolutionLexer lexer = new SolutionLexer(charStream);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        SolutionParser parser = new SolutionParser(tokens);
        
        ASD.Root root = parser.root().out;

        return root.solution2();
    }
}
